#!/bin/sh
# .Oo DERRICK - A Simple Network Stream Recorder
# Copyright (C) 2011-2012 Konrad Rieck (konrad@mlsec.org)
    
# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

# Apply configuration
case $arg in
    # Cluster nodes at TU Berlin
    node*)
        echo "# Configuration: Node"
        CC="gcc" \
        CPPFLAGS="-I $HOME/usr/include -L $HOME/usr/lib" \
        CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=native" \
        ./configure --prefix=$HOME/user
        ;;       
    # Konrad's sluggish laptop
    scarecrow*|twoface*|ltrieck*)
        echo "# Configuration: Twoface"
        CC="gcc" \
        CFLAGS="-DDEBUG -g -pedantic -pipe -O3" \
        ./configure --prefix=/opt/rieck --with-libnet=/usr/local
        ;;
    # VoIP system running somewhere
    fernsprechamt*)
        echo "# Configuration: Fernsprechamt"
        CFLAGS="-DDEBUG -g -pedantic -pipe -O2" \
        ./configure --prefix=/usr/local/prosec
        ;;
    # Default configuration
    *)    
        echo "# Configuration: Standard"
        CFLAGS="-g -pedantic -pipe -O3" \
        ./configure 
        ;;
esac

if test $? -gt 0 ; then
    echo "Error: Configuration failed"
    exit 1
fi

# Compile
make clean 
make -j 4 
